### ISSUE TITLE
why?

### ISSUE THREAD

**Issue by Drekazar** [Assasans/protanki-server#104]
Exception in thread "main" com.squareup.moshi.JsonEncodingException: Use JsonReader.setLenient(true) to accept malformed JSON at path $
        at com.squareup.moshi.JsonReader.syntaxError(JsonReader.java:243)
        at com.squareup.moshi.JsonUtf8Reader.checkLenient(JsonUtf8Reader.java:1152)
        at com.squareup.moshi.JsonUtf8Reader.doPeek(JsonUtf8Reader.java:384)
        at com.squareup.moshi.JsonUtf8Reader.peek(JsonUtf8Reader.java:206)
        at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:38)
        at com.squareup.moshi.JsonAdapter$3.fromJson(JsonAdapter.java:249)
        at com.squareup.moshi.JsonAdapter.fromJson(JsonAdapter.java:70)
        at jp.assasans.protanki.server.garage.GarageMarketRegistry.load(GarageMarketRegistry.kt:55)
        at jp.assasans.protanki.server.Server.run(Server.kt:48)
        at jp.assasans.protanki.server.MainKt.main(Main.kt:150)
        at jp.assasans.protanki.server.MainKt$main$6.invoke(Main.kt)
        at jp.assasans.protanki.server.MainKt$main$6.invoke(Main.kt)
        at kotlin.coroutines.intrinsics.IntrinsicsKt__IntrinsicsJvmKt$createCoroutineUnintercepted$$inlined$createCoroutineFromSuspendFunction$IntrinsicsKt__IntrinsicsJvmKt$1.invokeSuspend(IntrinsicsJvm.kt:205)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlin.coroutines.ContinuationKt.startCoroutine(Continuation.kt:115)
        at kotlin.coroutines.jvm.internal.RunSuspendKt.runSuspend(RunSuspend.kt:19)
        at jp.assasans.protanki.server.MainKt.main(Main.kt)
        
        меняю васп вот такая ошибка почему?

**Comment by Drekazar** [comment]
да я уже сделал
