### ISSUE TITLE
Почему, это может быть?

### ISSUE THREAD

**Issue by Londxd** [Assasans/protanki-server#115]
Failed to call BattleSelect::Fight handler
java.util.NoSuchElementException: Collection contains no element matching the predicate.
        at jp.assasans.protanki.server.battles.map.MapRegistryKt.getProplib(MapRegistry.kt:120)
        at jp.assasans.protanki.server.commands.handlers.LobbyHandler.fight(LobbyHandler.kt:148)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Instance.call(CallerImpl.kt:113)
        at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:108)
        at kotlin.reflect.jvm.internal.KCallableImpl.callDefaultMethod$kotlin_reflection(KCallableImpl.kt:159)
        at kotlin.reflect.full.KCallables.callSuspendBy(KCallables.kt:74)
        at jp.assasans.protanki.server.client.UserSocket.processPacket(UserSocket.kt:266)
        at jp.assasans.protanki.server.client.UserSocket.access$processPacket(UserSocket.kt:71)
        at jp.assasans.protanki.server.client.UserSocket$handle$3.invokeSuspend(UserSocket.kt:314)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
        
        это связано с картой которую я добавил всё прописал и такая ошибка

**Comment by Londxd** [comment]
Если что, я про proplibs.xml и map.xml не забыл, я заменил их.

**Comment by Assasans** [comment]
> at jp.assasans.protanki.server.battles.map.MapRegistryKt.getProplib(MapRegistry.kt:120)

Карта использует какую-то проплибу, которой нет в `proplibs.json`

**Comment by Londxd** [comment]
а, нужно Bush 3D Добавить

**Comment by Londxd** [comment]
Слушай а я могу просто вырезать Bush 3d? и всё

**Comment by Londxd** [comment]
@Assasans а в утилитах нету скрипта на прописку Proplibs.xml просто я хз думал карты делать а вот еще к картам же нужно proplibs.xml

**Comment by Londxd** [comment]
И немог бы ты мне дать свой дискорд, пожалуйста

**Comment by Assasans** [comment]
Из ТО? Если там совместимые с флеш версией модельки, то да

**Comment by Londxd** [comment]
Да из китай танков

**Comment by Londxd** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/103200197/181618509-f530c92d-7284-4ffa-9c5c-4a6d4ba72aa1.png)
 снова такая же херь как и раньше

**Comment by Londxd** [comment]
10001988 это птшный ресурс
просто и в прошлый раз такое же было

**Comment by Londxd** [comment]
я пока закрою ком
напиши дс пожалуйста

**Comment by Assasans** [comment]
> @Assasans а в утилитах нету скрипта на прописку Proplibs.xml

Он у меня локально на компе, завтра пушну

> И немог бы ты мне дать свой дискорд, пожалуйста

`Assasans#5469`, но я предпочитаю отвечать на сервере https://discord.gg/vtB36bXU (пока для этого проекта нет отдельного)

**Comment by Assasans** [comment]
>  снова такая же херь как и раньше

Вероятнее всего проплиба есть в `proplibs.xml`, но не в JSON файле карты

**Comment by Londxd** [comment]
> > снова такая же херь как и раньше
> 
> Вероятнее всего проплиба есть в `proplibs.xml`, но не в JSON файле карты

Да нет такой проп либы даже в пт нету
