### ISSUE TITLE
[Error] Creating a match results in an error

### ISSUE THREAD

**Issue by efsfssf** [Assasans/protanki-server#13]
When creating a match, the following error occurred.

Match Characteristics:
Mode: "Every man for himself"
Pro Battle: No
Closed battle: No

`[21:06:25.896 24/03/2022] [jp.assasans.protanki.server.client.UserSocket/ERROR]: Failed to call BattleCreate::CreateBattle handler
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Instance.call(CallerImpl.kt:113)
        at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:108)
        at kotlin.reflect.jvm.internal.KCallableImpl.callDefaultMethod$kotlin_reflection(KCallableImpl.kt:159)
        at kotlin.reflect.full.KCallables.callSuspendBy(KCallables.kt:74)
        at jp.assasans.protanki.server.client.UserSocket.processPacket(UserSocket.kt:243)
        at jp.assasans.protanki.server.client.UserSocket.access$processPacket(UserSocket.kt:56)
        at jp.assasans.protanki.server.client.UserSocket$handle$4.invokeSuspend(UserSocket.kt:318)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: java.util.NoSuchElementException: Collection contains no element matching the predicate.
        at jp.assasans.protanki.server.battles.map.MapRegistryKt.get(MapRegistry.kt:61)
        at jp.assasans.protanki.server.commands.handlers.LobbyHandler.createBattle(LobbyHandler.kt:203)
        ... 18 more`

**Comment by kuraysdev** [comment]
Not all maps have configs. only Kungur and Sandbox
maps configs located in
/src/main/resources/data/maps/
