### ISSUE TITLE
Cannot create battle

### ISSUE THREAD

**Issue by Colly001** [Assasans/protanki-server#98]
[jp.assasans.protanki.server.client.UserSocket/ERROR]: Failed to call BattleCreate::CreateBattle handler
com.squareup.moshi.JsonDataException: Required value 'equipmentConstraintsMode' missing at $
        at com.squareup.moshi.internal.Util.missingProperty(Util.java:660)
        at com.squareup.moshi.kotlin.reflect.KotlinJsonAdapter.fromJson(KotlinJsonAdapter.kt:105)
        at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:41)
        at com.squareup.moshi.JsonAdapter.fromJson(JsonAdapter.java:70)
        at jp.assasans.protanki.server.commands.CommandArgs$Companion.convert(CommandHandlerDescription.kt:33)
        at jp.assasans.protanki.server.client.UserSocket.processPacket(UserSocket.kt:259)
        at jp.assasans.protanki.server.client.UserSocket.access$processPacket(UserSocket.kt:73)
        at jp.assasans.protanki.server.client.UserSocket$handle$3.invokeSuspend(UserSocket.kt:318)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by kuraysdev** [comment]
Not enough data to reproduce the error
